name: ACE
version: 5.2
date: 2016-03-11
description: |
    Advanced Coset Enumerator

authors:
    - name: Greg Gamble
      url: http://staffhome.ecm.uwa.edu.au/~00021149
    - name: Alexander Hulpke
      url: http://www.math.colostate.edu/~hulpke
    - name: George Havas
      url: http://staff.itee.uq.edu.au/havas
    - name: Colin Ramsay
      url: mailto:cram@itee.uq.edu.au

maintainers:
    - name: Greg Gamble
      url: http://staffhome.ecm.uwa.edu.au/~00021149
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.7"

www: https://gap-packages.github.io/ace
readme: README
packageinfo: https://gap-packages.github.io/ace/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/ace/releases/download/v5.2/ace-5.2.tar.gz

abstract: |
    The <span class="pkgname">ACE</span> package provides both an    interactive and non-interactive interface with the Todd-Coxeter coset   enumeration functions of the ACE (Advanced Coset Enumerator) C program.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
