name: ACE
version: 5.1
date: 22/01/2012
description: Advanced Coset Enumerator

authors:
    - name: Greg Gamble
      url: http://school.maths.uwa.edu.au/~gregg
    - name: Alexander Hulpke
      url: http://www.math.colostate.edu/~hulpke
    - name: George Havas
      url: http://www.itee.uq.edu.au/~havas
    - name: Colin Ramsay
      url: http://www.itee.uq.edu.au/~cram

maintainers:
    - name: Greg Gamble
      url: http://school.maths.uwa.edu.au/~gregg

GAP: ">= 4.4"

www: http://school.maths.uwa.edu.au/~gregg/ACE/
readme: http://school.maths.uwa.edu.au/~gregg/ACE/README
packageinfo: http://school.maths.uwa.edu.au/~gregg/ACE/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://school.maths.uwa.edu.au/~gregg/ACE/ace-5.1.tar.gz

abstract: The <span class="pkgname">ACE</span> package provides both an      interactive and non-interactive interface with the Todd-Coxeter coset     enumeration functions of the ACE (Advanced Coset Enumerator) C program.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
